config/routes.rb
Rails.application.routes.draw do
  get '/comments/new',      :controller => 'comments', :action => 'new',    :as => 'new_comment'
  post '/comments',         :controller => 'comments', :action => 'create', :as => 'comments'

  get '/comments',          :controller => 'comments', :action => 'index'
  get '/comments/:id',      :controller => 'comments', :action => 'show',   :as => 'comment'

  get '/comments/:id/edit', :controller => 'comments', :action => 'edit',   :as => 'edit_comment'
  patch '/comments/:id',    :controller => 'comments', :action => 'update'

  delete '/comments/:id',   :controller => 'comments', :action => 'destroy'

  get("/ideas/new", {:controller => 'ideas', :action => 'new', :as => 'new_idea'})
  post("/ideas", {:controller => 'ideas', :action => 'create', :as => 'ideas' })

  get("/ideas/:id", {:controller => 'ideas', :action => 'show', :as => 'idea'})
  get("/ideas", {:controller => 'ideas', :action => 'index'})

  get("/ideas/:id/edit", {:controller => 'ideas', :action => 'edit', :as => 'edit_idea'})
  patch("/ideas/:id", {:controller => 'ideas', :action => 'update'})

  delete("/ideas/:id", {:controller => 'ideas', :action => 'destroy'})

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :contents, :idea_id, presence: true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :desc, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
    @idea = Idea.find(@comment.idea_id)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new
    @comment.contents = params[:contents]
    @comment.idea_id = params[:idea_id]

    if @comment.save
      respond_to do |format|
        format.html { redirect_to comments_url, :notice => "Comment created successfully." }
        format.js { render 'create'}
      end
    else
      render 'new'
    end
  end

  def edit
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html { render 'edit' }
      format.js { render 'edit' }
    end
  end

  def update
    @comment = Comment.find(params[:id])

    @comment.contents = params[:contents]
    @comment.idea_id = params[:idea_id]

    if @comment.save
      respond_to do |format|
        format.html { redirect_to comment_url(@comment.id), :notice => "Comment updated successfully." }
        format.js { render 'update' }
      end

    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, :notice => "Comment deleted." }
      format.js { render 'destroy'}
    end

  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def show
    @idea = Idea.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where({idea_id: @idea.id}).order(created_at: :desc)
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new
    @idea.desc = params[:desc]
    if @idea.save
      respond_to do |format|
        format.html {redirect_to idea_url(@idea.id)}
        format.js { render 'create'}
      end
    else
      render 'new'
    end
  end

  def edit
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html { render 'edit' }
      format.js { render 'edit' }
    end
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.desc = params[:desc]
    if @idea.save
      respond_to do |format|
        format.html {redirect_to idea_url(@idea.id)}
        format.js {render 'update'}
      end
    else
      render 'edit'
    end

  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.js { render 'destroy'}
    end

  end

  def index
    @ideas = Idea.all
    @idea = Idea.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment_list_item.html.erb
<li id="comment_<%= comment.id %>">
  <%= link_to comment.contents, comment_path(comment.id) %> |
  <%= link_to 'edit', edit_comment_path(comment.id), remote: true %>
</li>

app/views/comments/_inline_comment_form.html.erb
<%= form_tag comment_url(@comment.id), :method => "patch", :remote => true, :class => "form-horizontal", :id => "comment_#{@comment.id}_form" do %>
  <!-- Label and input for contents -->
  <div class="form-group">
    <label for="contents" class="sr-only">
      Contents
    </label>
    <div class="col-sm-6">
      <input type="text" id="contents" name="contents" placeholder="Contents" class="form-control" value="<%= @comment.contents %>">
    </div>
    <div class="col=sm-offset-6"></div>
  </div>
  </div>
  <input type="hidden" name="idea_id" value="<%= @comment.idea_id %>">

<% end %>

<!-- End responsive panel example -->

app/views/comments/create.js.erb
$('ul#comment-list').prepend('<%= j(render('comment_list_item', comment: @comment)) %>');

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').fadeOut();
console.log($('.isotope-container').isotope('layout'));

app/views/comments/edit.html.erb
<!-- Validation failure messages -->

<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Comment #<%= @comment.id %></h3>
      </div>
      <div class="panel-body">
        <%= form_tag comment_url(@comment.id), :method => "patch", :class => "form-horizontal" do %>
          <!-- Label and input for contents -->
          <div class="form-group">
            <label for="contents" class="col-sm-2 control-label">
              Contents
            </label>
            <div class="col-sm-10">
              <input type="text" id="contents" name="contents" placeholder="Contents" class="form-control" value="<%= @comment.contents %>">
            </div>
          </div>

          <div class="form-group">
            <label for="contents" class="col-sm-2 control-label">
              Idea ID
            </label>
            <div class="col-sm-10">
              <input type="text" id="contents" name="idea_id" placeholder="idea id" class="form-control" value="<%= @comment.idea_id %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Update Comment" class="btn btn-warning">
              or
              <%= link_to "Cancel", comment_url(@comment.id) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/comments/edit.js.erb
$('#comment_<%= @comment.id %>').replaceWith('<%= j(render 'inline_comment_form', comment: @comment) %>');

app/views/comments/index.html.erb
<div class="page-header">
  <h1>
    Comments
    <%= link_to new_comment_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Comments (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @comments.each do |comment| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item" id="comment_<%= comment.id %>">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Comment #<%= comment.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Contents</dt>
          <dd><%= comment.contents %></dd>

          <dt>Idea</dt>
          <% idea = Idea.find(comment.idea_id) %>
          <dd><%= idea.desc %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to comment_url(comment), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_comment_url(comment), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to comment_url(comment), :method => "delete", :remote => true, :data => { :confirm => "Do you really want to delete this comment?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/comments/new.html.erb
<!-- Validation failure messages -->

<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Comment</h3>
      </div>
      <div class="panel-body">
        <%= form_tag comments_url, :method => "post", :class => "form-horizontal" do %>
          <!-- Label and input for contents -->
          <div class="form-group">
            <label for="contents" class="col-sm-2 control-label">
              Contents
            </label>
            <div class="col-sm-10">
              <input type="text" id="contents" name="contents" placeholder="Contents" class="form-control" value="<%= @comment.contents %>">
            </div>
          </div>

          <div class="form-group">
            <label for="contents" class="col-sm-2 control-label">
              Idea ID
            </label>
            <div class="col-sm-10">
              <input type="text" id="contents" name="idea_id" placeholder="idea id" class="form-control" value="<%= @comment.idea_id %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Create Comment" class="btn btn-success">
              or
              <a href="/comments">Cancel</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/comments/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Comment #<%= @comment.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Contents</dt>
              <dd><%= @comment.contents %></dd>

              <dt>Idea</dt>
              <dd><%= link_to @idea.desc, idea_path(@idea.id) %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to comments_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_comment_url(@comment.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to comment_url(@comment.id), :method => "delete", :data => { :confirm => "Do you really want to delete this comment?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/comments/update.js.erb
$('#comment_<%= @comment.id %>_form').replaceWith("<%= j(render('comment_list_item', comment: @comment)) %>")

app/views/ideas/_idea.html.erb
<tr id="idea_<%= idea.id %>">
  <td><%= idea.desc %></td>
  <td><%= link_to 'Show', idea_path(idea.id)  %></td>
  <td><%= link_to 'Edit', edit_idea_path(idea.id), remote: true %></td>
  <td><%= link_to 'Destroy', idea_path(idea.id), :method => :delete, :remote => true  %></td>
</tr>

app/views/ideas/_inline_form_tr.html.erb
<tr id="idea_<%= @idea.id %>_form_tr">
  <td>
    <%= form_tag idea_path(@idea.id), method: :patch, remote: true do %>
      <input type="text" id="desc" name="desc" value="<%= @idea.desc %>">
    <% end %>
  </td>
</tr>

app/views/ideas/create.js.erb
$('table').append("<%= j(render('idea', idea: @idea)) %>");
$('#idea_<%= @idea.id %>').hide();
$('#idea_<%= @idea.id %>').fadeIn();
$('input#desc').val("");

app/views/ideas/destroy.js.erb
$("#idea_<%= @idea.id %>").fadeOut();

app/views/ideas/edit.html.erb
<h1>Edit idea #<%= @idea.id %></h1>
<% if @idea.errors %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_tag idea_path(@idea.id), :method => :patch do %>
  <label for="desc">Description:</label>
  <input type="text" id="desc" name="desc" value="<%= @idea.desc %>">
  <input type="submit">
<% end %>


<%= link_to 'Destroy', idea_path(@idea.id), :method => :delete  %> |
<%= link_to 'Back to index', ideas_path  %>

app/views/ideas/edit.js.erb
$('#idea_<%= @idea.id %>').replaceWith('<%= j(render('inline_form_tr')) %>');

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>
<h2>Add a new idea</h2>
<% if @idea.errors %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_tag ideas_path, remote: true do %>
  <label for="desc">Description:</label>
  <input type="text" id="desc" name="desc" value="<%= @idea.desc %>">
  <input type="submit">
<% end %>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>
  <% @ideas.each do |idea|  %>
    <%= render 'idea', idea: idea %>
  <% end %>
</table>

app/views/ideas/new.html.erb
<h1>Add a new idea</h1>
<% if @idea.errors %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_tag ideas_path do %>
  <label for="desc">Description:</label>
  <input type="text" id="desc" name="desc" value="<%= @idea.desc %>">
  <input type="submit">
<% end %>

app/views/ideas/show.html.erb
<h1><%= @idea.desc %></h1>
<%= link_to 'Edit', edit_idea_path(@idea.id)  %> |
<%= link_to 'Destroy', idea_path(@idea.id), :method => :delete  %> |
<%= link_to 'Back to index', ideas_path  %>

<h2>Comments</h2>
<!-- Validation failure messages -->

<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Comment</h3>
      </div>
      <div class="panel-body">
        <%= form_tag comments_url, :method => "post", :remote => true, :class => "form-horizontal" do %>
          <!-- Label and input for contents -->
          <div class="form-group">
            <label for="contents" class="col-sm-2 control-label">
              Contents
            </label>
            <div class="col-sm-10">
              <input type="text" id="contents" name="contents" placeholder="Contents" class="form-control" value="<%= @comment.contents %>">
            </div>
          </div>
          <input type="hidden" name="idea_id" value="<%= @idea.id %>">

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Create Comment" class="btn btn-success">
              or
              <a href="/comments">Cancel</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

<ul id="comment-list">
  <% @comments.each do |comment| %>
    <%= render 'comments/comment_list_item', comment: comment %>
  <% end %>
</ul>

app/views/ideas/update.js.erb
$('#idea_<%= @idea.id %>_form_tr').replaceWith('<%= j(render('idea', idea: @idea)) %>');
$('#idea_<%= @idea.id %>').hide();
$('#idea_<%= @idea.id %>').fadeIn();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>IdeaNotebook</title>


  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">IdeaNotebook</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/comments">Comments</a></li>
        <li><a href="/ideas">Ideas</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if 1 > 2 %>
          <li><a href="/users/edit">Oscar the Grouch</a></li>
          <li><a href="/users/sign_out" data-method="delete">Sign out</a></li>
        <% else %>
          <li><a href="/users/sign_up">Sign up</a></li>
          <li><a href="/users/sign_in">Sign in</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>